Fix/rules json
brenapp/referee.fyi pull request #105
Opened 2024-04-10 15:48 UTC by MiniMitre

Copied over all rule descriptions from the V4.0 game manual pdf and added to rules.json

Also, created seperate rules lists for VRC, VAIC, and VEXU. This makes the list shorter for VRC, and VEXU competitions, which makes it easier for referees to find the rule they want, by only showing rules relevant to each particular game.

Feedback wanted on the ordering of the rules. I do not think the order of the quick reference guide is the best, I have settled on:

[\<VAIG>]
[\<VAIT>]
[\<VAIR>]
(\<VUG>)
\<SG>
\<G>
(\<VUR>)
\<R>
\<S>
\<SC>
(\<VURS>)
\<RS>
(\<VUT>)
\<T>

This has required duplication, but works for now and can be fixed 'properly' next season

2024-04-10 16:53 UTC, brenapp requested changes

2024-04-10 16:53 UTC, brenapp commented on public/rules.json
> +              "description": " Only Drive Team Members, and only in the Alliance Station",
You should get rid of the leading space in every rule description. Is that to space it out in the Rules selector?

2024-04-11 20:30 UTC, brenapp requested changes

2024-04-11 20:30 UTC, brenapp commented on test/bulk/.env
> +VITE_REFEREE_FYI_BUILD_MODE=WC
Sorry I should have been more clear. The root directory of the project, you should make a .env file (it's gitignored) to include that setting

2024-04-11 20:30 UTC, brenapp commented on public/rules.json
> +      "ruleGroups": [
Should we make the IQ rule order consistent with the other programs?

2024-04-15 12:38 UTC, MiniMitre commented
Grouped together similar rules, so there are fewer sections in total. Decided on the following ordering based on the general likelihood of violations occuring.

Specific Game Rules
\<SG>

General / Safety Rules (
[\<VAIG>]
(\<VUG>)
\<G>
\<S>

Robot Rules
[\<VAIR>]
(\<VUR>)
\<R>

Scoring/Skills Rules
\<SC>
(\<VURS>)
\<RSC>

Tournament Rules
[\<VAIT>]
(\<VUT>)
\<T>

\<SC1> for IQ is a special case which is more likely to come up than usual for a scoring rule. However, for consistency the ordering is kept the same as VRC+

2024-04-15 14:30 UTC, brenapp approved these changes

2024-04-15 14:30 UTC, merged